# Generated by Django 2.2.6 on 2019-10-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191015_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='image',
        ),
    ]
