# Generated by Django 2.2.6 on 2019-11-12 13:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191015_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/Cogito_ntnu.svg', upload_to='static/images/'),
        ),
    ]
